# Generated by Django 3.1.6 on 2021-05-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponsmod',
            name='valid_to',
        ),
        migrations.AlterField(
            model_name='couponsmod',
            name='valid_from',
            field=models.DateTimeField(blank=True),
        ),
    ]
