# Generated by Django 3.1.6 on 2021-05-15 04:51

import coupons.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20210515_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponsmod',
            name='valid_to',
            field=models.DateTimeField(default=coupons.models.compute_default_to),
        ),
        migrations.AlterField(
            model_name='couponsmod',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
