# Generated by Django 3.1.6 on 2021-05-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20210515_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponsmod',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
