# Generated by Django 3.1.6 on 2021-05-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_couponsmod_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponsmod',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
